version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "daily"
    target-branch: "develop"
  
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      github-action-dependencies:
        update-types:
          - "minor"
          - "patch"
