services:
    geoip-filter:
      container_name: geoip-filter
      build:
        context: .
        dockerfile: Dockerfile
      image: geoipfilter
      volumes:
       - ${TRAEFIK_PROVIDER_DIR}:/rules
      environment:
        - MAXMIND_KEY=${MAXMIND_KEY}
        - COUNTRY_CODES=${COUNTRY_CODES}
        - SUB_CODES=${SUB_CODES}
      
