name: If dependabot updates dockerfile then update image

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'Dockerfile'

jobs:
  build:
    if: |
      github.event.pull_request.merged &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            mpdcampbell/traefik-geoip-filter:${{ steps.previoustag.outputs.tag }}
            mpdcampbell/traefik-geoip-filter:edge
